### ISSUE TITLE
C64 Koala export 

### ISSUE THREAD

**Issue by hohlinger** [Viza74/c64helperscriptsforaseprite#4]
Hey.
I got a problem with the Export Koala script and I do not know what happens. I was trying to export a sample pic (4 colors, c64 palette, 160x100 pixels) to Koala format but got the following error message:
https://community.aseprite.org/uploads/default/2c2b33892241d1e75097973eccaed26cd523c13d
Can anybody help me with that? Am I doing something wrong?
How can I get a koala pic out of Aseprite?
Thank you very much in advance!

**Comment by Viza74** [comment]
Hi,
I just checked the script here and it seems to work fine for me (Aseprite 1.2.17)

According to the error message on the screenshot, there is an extra '<' character in the "Export Koala.lua" at the 7th line in your script. There is no such char in the script on github, could you check if it is really there in yours?

(Or just try replacing that script from here, maybe it is damaged somehow?)

**Comment by hohlinger** [comment]
Hi.
Thank you very much for the answer. I checked it again and now it works. At the download there happened something weird and the lua files where in fact html files?! Strange. 
Thanks again for your help and a happy and healthy easter time.

**Comment by Viza74** [comment]
Cool, I'm happy that everything works!
Closing this issue now.
